# Generated by Django 3.2 on 2023-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('date_meeting', models.DateField()),
                ('place_meeting', models.CharField(blank=True, max_length=100)),
                ('topic_meeting', models.CharField(max_length=100)),
                ('comment_client', models.TextField(blank=True)),
            ],
        ),
    ]
