# Generated by Django 3.2 on 2023-02-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_meeting',
        ),
        migrations.RemoveField(
            model_name='client',
            name='place_meeting',
        ),
        migrations.RemoveField(
            model_name='client',
            name='topic_meeting',
        ),
    ]
